version: '3.8'
services:
  zero:
    image: dgraph/dgraph:latest
    ports:
      - "5080:5080"
      - "6080:6080"
    volumes:
      - dgraph_zero:/dgraph
    command: dgraph zero --my=zero:5080

  dgraph:
    image: dgraph/dgraph:latest
    ports:
      - "8080:8080"  # HTTP API
      - "9080:9080"  # gRPC API
    volumes:
      - dgraph_data:/dgraph
    command: dgraph alpha --my=dgraph:7080 --zero=zero:5080 --security whitelist=0.0.0.0/0
    depends_on:
      - zero

  ratel:
    image: dgraph/ratel:latest
    ports:
      - "8000:8000"
    depends_on:
      - dgraph

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  dgraph_zero:
  dgraph_data:
  redis_data: 