# docker-compose.yml
version: '3.8'
services:
  dgraph:
    image: dgraph/dgraph:latest
    ports:
      - "8080:8080"  # HTTP API
      - "9080:9080"  # gRPC API
      - "5080:5080"  # Internal communication
    volumes:
      - dgraph_data:/dgraph
    command: dgraph alpha --security whitelist=0.0.0.0/0

  ratel:
    image: dgraph/ratel:latest
    ports:
      - "8000:8000"
    depends_on:
      - dgraph

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  dgraph_data:
  redis_data: